### ISSUE TITLE
theme download failed

### ISSUE THREAD

**Issue by mafiuss** [Shopify/shopify_theme#118]
A fresh gem install/configuration returned the following error when downloading a theme

ruby-1.9.3-p545/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:57:in `asset_list': undefined method`collect' for nil:NilClass (NoMethodError)

**Comment by dillonbailey** [comment]
Issue with download of theme...

```
dpb$ theme download
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:57:in `asset_list': undefined method `collect' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:78:in `download'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/gems/shopify_theme-0.0.21/bin/theme:24:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/theme:23:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/theme:23:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_executable_hooks:15:in `<main>'
```
