### ISSUE TITLE
undefined method `load_file' for Psych:Module (NoMethodError)

### ISSUE THREAD

**Issue by whoisbenjamin** [Shopify/shopify_theme#139]
No an engineer, so not sure what's going wrong. 'theme' doesn't seem to want to work. Here's what I get spit back at me.

theme check
/Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:101:in `config': private method `load' called for Psych:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:139:in `shopify'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme.rb:134:in `check_config'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/lib/shopify_theme/cli.rb:40:in `check'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.21/bin/theme:24:in `<top (required)>'
	from /usr/bin/theme:23:in `load'
	from /usr/bin/theme:23:in `<main>'

Any thoughts?? Pretty urgent & critical.

**Comment by whoisbenjamin** [comment]
I've solved issue by uninstalling/installing the gem, but now can't configure — though now seem to be similar to another open issue.
