### ISSUE TITLE
Gem:LoadError

### ISSUE THREAD

**Issue by TheNix** [Shopify/shopify_theme#144]
When I attempt to run any command (like  `theme configure`), I get the following error:

```
/usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'shopify_theme' (>= 0) among 31 total gem(s) (Gem::LoadError)
	from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
	from /usr/local/Cellar/ruby/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
	from /usr/bin/theme:22:in `<main>'
```

What do?

I have v0.0.22 installed (via Bundler).
I am in OSX Yosemite (10.2.2). Ruby is v2.1.1.

This issue may or may not be related to https://github.com/Shopify/shopify_theme/issues/133

**Comment by TheNix** [comment]
Nevermind. I messed something up in Bundler, so it showed up as installed (but in the wrong path).
