### ISSUE TITLE
Theme upload command error

### ISSUE THREAD

**Issue by cezr** [Shopify/shopify_theme#145]
When running the theme upload assets/* command I continue to get a `load': syntax error on line 26, col 14: 1b", { "x"=>"ht' (ArgumentError) ...`

The error displayed in the terminal (using shopify_theme-0.0.22 on Ruby 1.9+):

`Computer-iMac:project user7$ theme upload assets/theme.js.liquid`

```
[15:32:19] Uploading: assets/theme.js.liquid/Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/syck.rb:135:in `load': syntax error on line 26, col 14: `b", { "x"=>"ht' (ArgumentError)
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/syck.rb:135:in `load'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme.rb:99:in `config'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme.rb:137:in `shopify'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme.rb:71:in `send_asset'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme/cli.rb:234:in `block in send_asset'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme/cli.rb:297:in `show_during'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme/cli.rb:233:in `send_asset'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme/cli.rb:106:in `block in upload'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme/cli.rb:105:in `each'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/lib/shopify_theme/cli.rb:105:in `upload'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/user7/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.22/bin/theme:25:in `<top (required)>'
	from /Users/user7/.rvm/gems/ruby-1.9.3-p448/bin/theme:23:in `load'
	from /Users/user7/.rvm/gems/ruby-1.9.3-p448/bin/theme:23:in `<main>'
	from /Users/user7/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
	from /Users/user7/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by csaunders** [comment]
are you sure your js file is valid Liquid?

**Comment by cezr** [comment]
Yes. I just figured it out. 
Under the config.yml there needs to be a newline after the :ignore_files:
I believe the issue was loading/reading the config file.

i.e. 
:api_key: #################
:password: #################
:store: example.myshopify.com
:theme_id: 
:ignore_files:

**Comment by gionkunz** [comment]
Just experienced that too. Newline at EOF fixes it. +1 for a fix.
