### ISSUE TITLE
Gem does not gracefully handle when API is down.

### ISSUE THREAD

**Issue by mlkhui** [Shopify/shopify_theme#146]
Edit: When the API is down very cryptic errors are thrown by the gem.

-------

Original Issue:
Is this a Shopify problem?

```
khui-ltm3:uncl-mobile khui$ theme download
/Users/khui/.rvm/gems/ruby-1.9.3-p545/gems/bundler-1.5.3/lib/bundler.rb:295: warning: Insecure world writable dir /usr/local in PATH, mode 040777
:ignore_files: is deprecated for a white list, use :whitelist_files: instead
/Users/khui/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:763:in `initialize': Operation timed out - connect(2) (Errno::ETIMEDOUT)
	from /Users/khui/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:763:in `open'
	from /Users/khui/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
	from /Users/khui/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /Users/khui/.rvm/rubies/ruby-1.9.3-


```

**Comment by csaunders** [comment]
I don't know. Is it happening all the time or just sometimes?

Did you check out https://status.shopify.com/ to see if there was anything weird going on with the API?

Is your configuration valid?

**Comment by mlkhui** [comment]
problem went away.

**Comment by csaunders** [comment]
The issue isn't actually resolved, it just seems like the API was down.
