### ISSUE TITLE
SSL Error when running 'theme download' on Windows

### ISSUE THREAD

**Issue by leeatkinson** [Shopify/shopify_theme#159]
I have just installed this gem on Windows, I've set up the config using 'theme configure', and when I run 'theme download' for the first time, I'm getting the error below. I have tried the recommendation of downloading the cert file and specifying SSL_CERT_FILE environment variable, but no luck. I've checked that the store is correct in config.yml.

```
C:\Users\Lee\Documents\Shopify>theme download
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OpenSSL::SSL::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.5/lib/httparty.rb:460:in `get'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.22/lib/shopify_theme.rb:52:in `asset_list'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.22/lib/shopify_theme/cli.rb:81:in `download'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.22/bin/theme:25:in `<top (required)>'
        from C:/Ruby22-x64/bin/theme:23:in `load'
        from C:/Ruby22-x64/bin/theme:23:in `<main>'
```

**Comment by csaunders** [comment]
Try using [themekit](http://themekit.cat) instead. You'll need to install it somewhere, but the [installation instructions](http://themekit.cat/install/#windows) should help you.

**Comment by heyjonmanning** [comment]
I had a very similar issue as well. Installing Theme Kit fixed the SSL errors for me.

**Comment by csaunders** [comment]
I've deployed a new gem version. This one includes a bundled CA certificate that should resolve any SSL errors Windows users have been experiencing. I did the testing on a Windows 8.1 VM to ensure that it behaves the way we expect.

Please let me know if you have any issues.
