### ISSUE TITLE
theme create crashes

### ISSUE THREAD

**Issue by skywinder** [Shopify/shopify_theme#177]
I run `theme create` right after installation and got crash (but yml was created)

```
/Users/petrkorolev/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/header.rb:17:in `block in initialize_http_header': undefined method `strip' for nil:NilClass (NoMethodError)
	from /Users/petrkorolev/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/header.rb:15:in `each'
	from /Users/petrkorolev/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/header.rb:15:in `initialize_http_header'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/httparty-0.13.7/lib/httparty/request.rb:176:in `setup_raw_request'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/httparty-0.13.7/lib/httparty/request.rb:114:in `perform'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme.rb:143:in `get_index'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/api_checker.rb:35:in `test_connectivity'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:41:in `check'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:63:in `configure'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/theme:23:in `load'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/theme:23:in `<main>'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by csaunders** [comment]
pretty sure it creates the file right away... I guess if you give it no arguments it should yell at you and echo what it's help text is.

**Comment by skywinder** [comment]
@csaunders can you clarify: should I pass some params after `create` ?

**Comment by ar7casper** [comment]
@skywinder Did you solve it somehow? I get the same thing.

**Comment by skywinder** [comment]
@ar7casper  yes. the file was created. But this issue is about `theme` - this command still crashes.

**Comment by ar7casper** [comment]
@skywinder - Had the same problem. 
When you first create the config.yml file, you get the errors. after it has been created, open the file and edit the field. Then run the commands and it should work.
My problem occurred due to a typo in the config file.
