### ISSUE TITLE
`rescue in rbuf_fill' timeout error

### ISSUE THREAD

**Issue by discernmarketing** [Shopify/shopify_theme#180]
I keep getting this error when trying to upload files using the watch command. I've looked around and can't seem to find the solution. Any thoughts or suggestions? Thank you in advance for any help.

```
[10:38:21] Uploading: assets/finish-breeze-fusion-4202.jpg/Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /Users/M***/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/httparty-0.13.7/lib/httparty.rb:502:in `put'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme.rb:76:in `send_asset'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:267:in `block in send_asset'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:330:in `show_during'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:266:in `send_asset'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:183:in `block in watch'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:228:in `block in watcher'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/filewatcher-0.5.2/lib/filewatcher.rb:55:in `watch'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:227:in `watcher'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:170:in `watch'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/M***/.rvm/gems/ruby-2.2.3/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /Users/M***/.rvm/gems/ruby-2.2.3/bin/theme:23:in `load'
	from /Users/M***/.rvm/gems/ruby-2.2.3/bin/theme:23:in `<main>'
	from /Users/M***/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/M***/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by discernmarketing** [comment]
There appears to be something wrong with my theme. I tried a fresh install and the watch functions perfectly.
