### ISSUE TITLE
[Theme Configure] Keep getting undefined method 'to_yaml'

### ISSUE THREAD

**Issue by rileybracken** [Shopify/shopify_theme#183]
When running `theme configure` I keep getting 
`'configure': undefined method 'to_yaml' for hash object (NoMethodError)`

When I run `theme systeminfo` I get
Ruby: v2.2.0-p0
Operating System: x86_64-darwin14
Thor: v0.19.1
Listen: v3.0.3
HTTParty: v0.13.7
Launchy: v2.4.3

If I run `theme check` I get
`undefined method 'strip' for nil:NilClass (NoMethodError)`

If I run `theme bootstrap`
it will Successfully create Timber using Shopify Timber lates
then Create the directory named Timber
then try to Save configuration to Timber
and gives me 
`'configure': undefined method 'to_yaml' for has object (NoMethodError)`

This is off a fresh install of the gem, never have used it before and was interested in trying it out.

**Comment by conrman** [comment]
+1 I'm getting this error as well. Although, when I run `theme systeminfo` I get
```
Ruby: v2.2.3-p173
Operating System: x86_64-darwin15
Thor: v0.19.1
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- listen/version (LoadError)
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:194:in `block in systeminfo'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:193:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:193:in `systeminfo'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /usr/local/bin/theme:23:in `load'
	from /usr/local/bin/theme:23:in `<main>'
```


Fresh gem install and tried everything from scratch as well but still came up with same error:
```
'configure': undefined method 'to_yaml' for has object (NoMethodError)
```

**Comment by stefanedberg** [comment]
+1

Fresh gem install on OS X 10.11.3.

**theme configure**

```
/Users/stefan/.rvm/gems/ruby-2.2.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:62:in `configure': undefined method `to_yaml' for #<Hash:0x007f9162988af0> (NoMethodError)
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/theme:23:in `load'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/theme:23:in `<main>'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**theme systeminfo**

```
Ruby: v2.2.0-p0
Operating System: x86_64-darwin14
Thor: v0.19.1
/Users/stefan/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- listen/version (LoadError)
	from /Users/stefan/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:194:in `block in systeminfo'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:193:in `each'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:193:in `systeminfo'
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/stefan/.rvm/gems/ruby-2.2.0@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/theme:23:in `load'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/theme:23:in `<main>'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/stefan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by justinmulwee** [comment]
+1 same error.

OSX 10.11.3 with a fresh, updated gem. Looks like this bug was reported months ago. No word from the devs? Weak...

**Comment by PendragonDevelopment** [comment]
Got the same error for the `require listen/version` on `theme systeminfo`, did a fresh install of listen (`gem install listen` -> 3.1.5) and it's good to go now. HTH.
