### ISSUE TITLE
Error when replace assets

### ISSUE THREAD

**Issue by skywinder** [Shopify/shopify_theme#185]
```
theme replace assets/
Are you sure you want to completely replace your shop theme assets? This is not undoable.
Continue? (Y/N):  Y
[11:33:58] Removed: assets/
/Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:258:in `read': Is a directory @ io_fread - assets/ (Errno::EISDIR)
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:258:in `send_asset'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:148:in `block in replace'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:147:in `each'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:147:in `replace'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/theme:23:in `load'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/theme:23:in `<main>'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by maxackerman** [comment]
same thing happening for me:

```
theme replace
Are you sure you want to completely replace your shop theme assets? This is not undoable.
Continue? (Y/N):  Y
/Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:144:in `=~': type mismatch: String given (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:144:in `block (2 levels) in replace'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:144:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:144:in `any?'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:144:in `block in replace'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:143:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:143:in `replace'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
	from /usr/local/bin/theme:23:in `load'
	from /usr/local/bin/theme:23:in `<main>'
```

**Comment by tyler-king** [comment]
Same thing for me... sad theres no fix yet.

**Comment by fourfour** [comment]
+1

**Comment by bhekuwenza** [comment]
Thank you @tyler-king !!!

https://github.com/tyler-king/shopify_theme

c'mon shopify! =/

**Comment by Cam** [comment]
@marcosalles thanks! That fix worked for me :)

**Comment by marcusYKT** [comment]
@marcosalles that also worked me, thanks very much!

**Comment by Jorybraun** [comment]
did this ever get fixed?

**Comment by marcosalles** [comment]
@Jorybraun nope. I'm still using my fork. I think the project has been abandoned.

**Comment by tyler-king** [comment]
@marcosalles when I was at Unite this year they mentioned Theme Kit is what is to be used now. I'm on my phone but I believe it's http://themekit.cat
